services:
  - type: web
    name: retorno-obra-api
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: LN_USERNAME
        value: igor.pessoa@eletrofrio.com.br
      - key: LN_PASSWORD
        value: Douglas@2024a
    plan: free
    autoDeploy: true
