services:
  - type: web
    name: retorno-obra-api
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn deploy_retorno_obra_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LN_USERNAME
        value: igor.pessoa@eletrofrio.com.br
      - key: LN_PASSWORD
        value: Douglas@2024a
    plan: free
    autoDeploy: true
