services:
  - type: web
    name: retorno-obra-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn deploy_retorno_obra_api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: LN_USERNAME
        value: igor.pessoa@eletrofrio.com.br
      - key: LN_PASSWORD
        value: Douglas@2024a
