services:
  - type: web
    name: deploy-controle-de-materiais
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn deploy_retorno_obra_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: USERNAME
        value: igor.pessoa@eletrofrio.com.br
      - key: PASSWORD
        value: Douglas@2024a
