services:
  - type: web
    name: deploy-controle-de-materiais
    env: python
    plan: free
    buildCommand: |
      # Instala dependências básicas
      apt-get update
      apt-get install -y wget unzip curl gnupg
      
      # Instala o Google Chrome
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb

      # Descobre a versão do Chrome instalada
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')

      # Baixa o ChromeDriver correspondente
      wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip"
      unzip /tmp/chromedriver.zip -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver

      # Instala dependências do Python
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn deploy_retorno_obra_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: USERNAME
        value: igor.pessoa@eletrofrio.com.br
      - key: PASSWORD
        value: Douglas@2024a
